import YAML from "yaml";
import type { HostConfig, Registry, ServiceConfig } from "./schemas.js";

export function renderCaddyfile(host: HostConfig, registry: Registry): string {
  const lines: string[] = [
    "# GENERATED BY porch - DO NOT EDIT",
    "",
    "{",
    `\temail ${host.acmeEmail}`,
    "}",
    "",
    "(porch_common) {",
    "\tencode zstd gzip",
    "\theader {",
    "\t\tX-Content-Type-Options nosniff",
    "\t\tReferrer-Policy strict-origin-when-cross-origin",
    "\t\tX-Frame-Options DENY",
    "\t}",
    "}",
    "",
  ];

  for (const service of registry.services) {
    lines.push(...renderServiceRoutes(service), "");
  }

  return `${lines.join("\n").trimEnd()}\n`;
}

export function renderEdgeCompose(host: HostConfig): string {
  return YAML.stringify({
    services: {
      caddy: {
        image: "caddy:2.9-alpine",
        container_name: "porch-caddy",
        restart: "unless-stopped",
        ports: ["80:80", "443:443"],
        volumes: [
          "./Caddyfile:/etc/caddy/Caddyfile:ro",
          "caddy_data:/data",
          "caddy_config:/config",
        ],
        networks: [host.network],
      },
    },
    networks: {
      [host.network]: {
        external: true,
      },
    },
    volumes: {
      caddy_data: null,
      caddy_config: null,
    },
  });
}

export function renderAppCompose(service: ServiceConfig, network: string): string {
  const environment = Object.keys(service.env).length > 0 ? service.env : undefined;

  return YAML.stringify({
    services: {
      web: {
        image: `\${WEB_IMAGE:-${service.image ?? `ghcr.io/OWNER/${service.id}:latest`}}`,
        container_name: service.upstream.container,
        restart: "unless-stopped",
        ...(environment ? { environment } : {}),
        networks: [network],
      },
    },
    networks: {
      [network]: {
        external: true,
      },
    },
  });
}

function renderServiceRoutes(service: ServiceConfig): string[] {
  const lines: string[] = [];
  const [primaryDomain, ...aliases] = service.domains;

  lines.push(`${primaryDomain} {`);
  lines.push("\timport porch_common");
  lines.push(`\treverse_proxy ${service.upstream.container}:${service.upstream.port}`);
  lines.push("}");

  for (const domain of aliases) {
    lines.push("");
    lines.push(`${domain} {`);
    lines.push("\timport porch_common");
    lines.push(`\treverse_proxy ${service.upstream.container}:${service.upstream.port}`);
    lines.push("}");
  }

  if (service.wwwRedirect && !primaryDomain.startsWith("www.")) {
    lines.push("");
    lines.push(`www.${primaryDomain} {`);
    lines.push(`\tredir https://${primaryDomain}{uri} permanent`);
    lines.push("}");
  }

  return lines;
}
